version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: src/Zuge.UI/Zuge.UI.Server/Dockerfile
    depends_on:
      - "db"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
#     - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_HTTP_PORTS=8080
      - CONNECTIONSTRINGS__AUTHENTICATIONCONNECTION=Database=Authentication;Host=db;Password=postgres;Username=postgres
      - CONNECTIONSTRINGS__DATACONNECTION=Database=Data;Host=db;Password=postgres;Username=postgres
    ports:
      - "5197:8080"
#     - "7209:8081"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
  
  db:
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: