// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Zuge.Infrastructure;

#nullable disable

namespace Zuge.Infrastructure.DomainMigrations
{
    [DbContext(typeof(UnitOfWork))]
    [Migration("20240213102148_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Zuge.Domain.Journey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Train")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Journey");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = new TimeSpan(0, 1, 43, 0, 0),
                            Price = 10m,
                            Train = "Juna 1"
                        },
                        new
                        {
                            Id = 2,
                            Duration = new TimeSpan(0, 1, 41, 0, 0),
                            Price = 10m,
                            Train = "Juna 1"
                        });
                });

            modelBuilder.Entity("Zuge.Domain.Stop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ArrivesAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ArrivesFrom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DepartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DepartsFrom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<int>("JourneyId")
                        .HasColumnType("integer");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Stop");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivesAt = new DateTimeOffset(new DateTime(2024, 2, 13, 5, 57, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ArrivesFrom = "Keuruu",
                            DepartsAt = new DateTimeOffset(new DateTime(2024, 2, 13, 5, 57, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartsFrom = "Keuruu",
                            Duration = new TimeSpan(0, 0, 0, 0, 0),
                            JourneyId = 1,
                            Ordinal = 1
                        },
                        new
                        {
                            Id = 2,
                            ArrivesAt = new DateTimeOffset(new DateTime(2024, 2, 13, 6, 11, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ArrivesFrom = "Keuruu",
                            DepartsAt = new DateTimeOffset(new DateTime(2024, 2, 13, 6, 19, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartsFrom = "Haapamäki",
                            Duration = new TimeSpan(0, 0, 14, 0, 0),
                            JourneyId = 1,
                            Ordinal = 2
                        },
                        new
                        {
                            Id = 3,
                            ArrivesAt = new DateTimeOffset(new DateTime(2024, 2, 13, 6, 28, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ArrivesFrom = "Haapamäki",
                            DepartsAt = new DateTimeOffset(new DateTime(2024, 2, 13, 6, 29, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartsFrom = "Kolho",
                            Duration = new TimeSpan(0, 0, 9, 0, 0),
                            JourneyId = 1,
                            Ordinal = 3
                        },
                        new
                        {
                            Id = 4,
                            ArrivesAt = new DateTimeOffset(new DateTime(2024, 2, 13, 6, 38, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ArrivesFrom = "Kolho",
                            DepartsAt = new DateTimeOffset(new DateTime(2024, 2, 13, 6, 40, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartsFrom = "Vilppula",
                            Duration = new TimeSpan(0, 0, 9, 0, 0),
                            JourneyId = 1,
                            Ordinal = 4
                        },
                        new
                        {
                            Id = 5,
                            ArrivesAt = new DateTimeOffset(new DateTime(2024, 2, 13, 6, 58, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ArrivesFrom = "Vilppula",
                            DepartsAt = new DateTimeOffset(new DateTime(2024, 2, 13, 6, 59, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartsFrom = "Juupajoki",
                            Duration = new TimeSpan(0, 0, 18, 0, 0),
                            JourneyId = 1,
                            Ordinal = 5
                        },
                        new
                        {
                            Id = 6,
                            ArrivesAt = new DateTimeOffset(new DateTime(2024, 2, 13, 7, 9, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ArrivesFrom = "Juupajoki",
                            DepartsAt = new DateTimeOffset(new DateTime(2024, 2, 13, 7, 10, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartsFrom = "Orivesi Keskusta",
                            Duration = new TimeSpan(0, 0, 10, 0, 0),
                            JourneyId = 1,
                            Ordinal = 6
                        },
                        new
                        {
                            Id = 7,
                            ArrivesAt = new DateTimeOffset(new DateTime(2024, 2, 13, 7, 14, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ArrivesFrom = "Orivesi Keskusta",
                            DepartsAt = new DateTimeOffset(new DateTime(2024, 2, 13, 7, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartsFrom = "Orivesi",
                            Duration = new TimeSpan(0, 0, 4, 0, 0),
                            JourneyId = 1,
                            Ordinal = 7
                        },
                        new
                        {
                            Id = 8,
                            ArrivesAt = new DateTimeOffset(new DateTime(2024, 2, 13, 7, 40, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ArrivesFrom = "Orivesi",
                            DepartsAt = new DateTimeOffset(new DateTime(2024, 2, 13, 7, 40, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartsFrom = "Tampere",
                            Duration = new TimeSpan(0, 0, 25, 0, 0),
                            JourneyId = 1,
                            Ordinal = 8
                        },
                        new
                        {
                            Id = 9,
                            ArrivesAt = new DateTimeOffset(new DateTime(2024, 2, 13, 8, 6, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ArrivesFrom = "Tampere",
                            DepartsAt = new DateTimeOffset(new DateTime(2024, 2, 13, 8, 6, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartsFrom = "Tampere",
                            Duration = new TimeSpan(0, 0, 0, 0, 0),
                            JourneyId = 2,
                            Ordinal = 1
                        },
                        new
                        {
                            Id = 10,
                            ArrivesAt = new DateTimeOffset(new DateTime(2024, 2, 13, 8, 31, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ArrivesFrom = "Tampere",
                            DepartsAt = new DateTimeOffset(new DateTime(2024, 2, 13, 8, 32, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartsFrom = "Orivesi",
                            Duration = new TimeSpan(0, 0, 25, 0, 0),
                            JourneyId = 2,
                            Ordinal = 2
                        },
                        new
                        {
                            Id = 11,
                            ArrivesAt = new DateTimeOffset(new DateTime(2024, 2, 13, 8, 35, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ArrivesFrom = "Orivesi",
                            DepartsAt = new DateTimeOffset(new DateTime(2024, 2, 13, 8, 36, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartsFrom = "Orivesi Keskusta",
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            JourneyId = 2,
                            Ordinal = 3
                        },
                        new
                        {
                            Id = 12,
                            ArrivesAt = new DateTimeOffset(new DateTime(2024, 2, 13, 8, 46, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ArrivesFrom = "Orivesi Keskusta",
                            DepartsAt = new DateTimeOffset(new DateTime(2024, 2, 13, 8, 47, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartsFrom = "Juupajoki",
                            Duration = new TimeSpan(0, 0, 10, 0, 0),
                            JourneyId = 2,
                            Ordinal = 4
                        },
                        new
                        {
                            Id = 13,
                            ArrivesAt = new DateTimeOffset(new DateTime(2024, 2, 13, 9, 6, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ArrivesFrom = "Juupajoki",
                            DepartsAt = new DateTimeOffset(new DateTime(2024, 2, 13, 9, 7, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartsFrom = "Vilppula",
                            Duration = new TimeSpan(0, 0, 19, 0, 0),
                            JourneyId = 2,
                            Ordinal = 5
                        },
                        new
                        {
                            Id = 14,
                            ArrivesAt = new DateTimeOffset(new DateTime(2024, 2, 13, 9, 14, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ArrivesFrom = "Vilppula",
                            DepartsAt = new DateTimeOffset(new DateTime(2024, 2, 13, 9, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartsFrom = "Kolho",
                            Duration = new TimeSpan(0, 0, 7, 0, 0),
                            JourneyId = 2,
                            Ordinal = 6
                        },
                        new
                        {
                            Id = 15,
                            ArrivesAt = new DateTimeOffset(new DateTime(2024, 2, 13, 9, 25, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ArrivesFrom = "Kolho",
                            DepartsAt = new DateTimeOffset(new DateTime(2024, 2, 13, 9, 33, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartsFrom = "Haapamäki",
                            Duration = new TimeSpan(0, 0, 10, 0, 0),
                            JourneyId = 2,
                            Ordinal = 7
                        },
                        new
                        {
                            Id = 16,
                            ArrivesAt = new DateTimeOffset(new DateTime(2024, 2, 13, 9, 47, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ArrivesFrom = "Kolho",
                            DepartsAt = new DateTimeOffset(new DateTime(2024, 2, 13, 9, 47, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartsFrom = "Keuruu",
                            Duration = new TimeSpan(0, 0, 14, 0, 0),
                            JourneyId = 2,
                            Ordinal = 8
                        });
                });

            modelBuilder.Entity("Zuge.Domain.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("JourneyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Ticket");
                });
#pragma warning restore 612, 618
        }
    }
}
